// <auto-generated />
namespace AFS.NET_developer_test.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EditTranslationAddSuccessAndContents : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditTranslationAddSuccessAndContents));
        
        string IMigrationMetadata.Id
        {
            get { return "201808212314112_EditTranslationAddSuccessAndContents"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
