// <auto-generated />
namespace AFS.NET_developer_test.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addFewRequiredToTranslationModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addFewRequiredToTranslationModels));
        
        string IMigrationMetadata.Id
        {
            get { return "201808222002488_addFewRequiredToTranslationModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
